services:
  db:
    image: mysql:8
    container_name: proyecto_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: proyecto_backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: appdb
      DB_USER: root
      DB_PASSWORD: clave123
      JWT_SECRET: recepbox_dev_secret

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: proyecto_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_AUTH_API_URL: http://localhost:3001/api/auth

volumes:
  mysql_data:
