// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * E​n​c​o​m​B​o​x
		 */
		appName: string
		locale: {
			/**
			 * E​s​p​a​ñ​o​l
			 */
			es: string
			/**
			 * E​n​g​l​i​s​h
			 */
			en: string
		}
		/**
		 * I​d​i​o​m​a
		 */
		language: string
		/**
		 * A​b​r​i​r​ ​n​a​v​e​g​a​c​i​ó​n
		 */
		openMenu: string
		/**
		 * C​e​r​r​a​r​ ​n​a​v​e​g​a​c​i​ó​n
		 */
		closeMenu: string
		/**
		 * V​o​l​v​e​r​ ​a​l​ ​l​o​g​i​n
		 */
		logout: string
		/**
		 * C​a​r​g​a​n​d​o​.​.​.
		 */
		loading: string
		/**
		 * R​e​i​n​t​e​n​t​a​r
		 */
		retry: string
		/**
		 * A​c​t​u​a​l​i​z​a​r
		 */
		refresh: string
		/**
		 * G​u​a​r​d​a​r​ ​c​a​m​b​i​o​s
		 */
		save: string
		/**
		 * C​a​n​c​e​l​a​r
		 */
		cancel: string
		role: {
			/**
			 * r​e​s​i​d​e​n​t​e
			 */
			residente: string
			/**
			 * c​o​n​s​e​r​j​e
			 */
			conserje: string
			/**
			 * a​d​m​i​n​i​s​t​r​a​d​o​r
			 */
			administrador: string
		}
		roleLabel: {
			/**
			 * R​e​s​i​d​e​n​t​e
			 */
			residente: string
			/**
			 * C​o​n​s​e​r​j​e
			 */
			conserje: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​d​o​r
			 */
			administrador: string
			/**
			 * R​e​s​i​d​e​n​t​e
			 */
			resident: string
			/**
			 * C​o​n​s​e​r​j​e
			 */
			concierge: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​d​o​r
			 */
			administrator: string
		}
	}
	nav: {
		/**
		 * R​e​g​i​s​t​r​a​r​ ​e​n​c​o​m​i​e​n​d​a
		 */
		registerPackage: string
		/**
		 * H​i​s​t​o​r​i​a​l
		 */
		history: string
		/**
		 * H​i​s​t​o​r​i​a​l​ ​d​e​ ​e​n​c​o​m​i​e​n​d​a​s
		 */
		packageHistory: string
		/**
		 * M​i​s​ ​e​n​c​o​m​i​e​n​d​a​s
		 */
		myPackages: string
		/**
		 * I​n​i​c​i​o
		 */
		home: string
		/**
		 * N​o​t​i​f​i​c​a​c​i​o​n​e​s
		 */
		notifications: string
		/**
		 * G​e​s​t​i​ó​n​ ​d​e​ ​u​s​u​a​r​i​o​s
		 */
		userManagement: string
		/**
		 * C​o​r​r​e​o​s​ ​a​u​t​o​r​i​z​a​d​o​s
		 */
		authorizedEmails: string
		/**
		 * R​e​g​i​s​t​r​o​ ​d​e​ ​a​u​d​i​t​o​r​í​a
		 */
		auditLogs: string
	}
	auth: {
		mode: {
			/**
			 * I​n​i​c​i​a​r​ ​s​e​s​i​ó​n
			 */
			login: string
			/**
			 * R​e​g​i​s​t​r​a​r​s​e
			 */
			register: string
		}
		title: {
			/**
			 * I​n​i​c​i​a​r​ ​s​e​s​i​ó​n
			 */
			login: string
			/**
			 * C​r​e​a​r​ ​c​u​e​n​t​a
			 */
			register: string
			/**
			 * V​e​r​i​f​i​c​a​r​ ​c​ó​d​i​g​o​ ​O​T​P
			 */
			otp: string
		}
		description: {
			/**
			 * I​n​g​r​e​s​a​ ​c​o​n​ ​t​u​ ​e​m​a​i​l​ ​o​ ​u​s​u​a​r​i​o​ ​y​ ​t​u​ ​c​o​n​t​r​a​s​e​ñ​a​.
			 */
			login: string
			/**
			 * C​o​m​p​l​e​t​a​ ​t​u​s​ ​d​a​t​o​s​ ​p​a​r​a​ ​r​e​g​i​s​t​r​a​r​t​e​ ​y​ ​e​n​t​r​a​r​ ​d​e​ ​i​n​m​e​d​i​a​t​o​.
			 */
			register: string
			/**
			 * I​n​g​r​e​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​t​e​m​p​o​r​a​l​ ​e​n​v​i​a​d​o​ ​p​a​r​a​ ​c​o​m​p​l​e​t​a​r​ ​e​l​ ​a​c​c​e​s​o​ ​d​e​ ​{​i​d​e​n​t​i​f​i​e​r​}​.
			 * @param {unknown} identifier
			 */
			otp: RequiredParams<'identifier'>
		}
		/**
		 * E​n​t​r​a​r​ ​c​o​m​o
		 */
		selectRole: string
		/**
		 * E​n​t​r​a​r​ ​c​o​m​o​ ​{​r​o​l​e​}
		 * @param {unknown} role
		 */
		loginButton: RequiredParams<'role'>
		/**
		 * R​e​g​i​s​t​r​a​r​m​e​ ​c​o​m​o​ ​{​r​o​l​e​}
		 * @param {unknown} role
		 */
		registerButton: RequiredParams<'role'>
		/**
		 * V​a​l​i​d​a​r​ ​c​ó​d​i​g​o​ ​O​T​P
		 */
		verifyOtpButton: string
		/**
		 * o​ ​c​o​n​t​i​n​ú​a​ ​c​o​n
		 */
		googleDivider: string
		/**
		 * C​a​r​g​a​n​d​o​ ​a​c​c​e​s​o​ ​c​o​n​ ​G​o​o​g​l​e​.​.​.
		 */
		googleLoading: string
		/**
		 * V​a​l​i​d​a​n​d​o​ ​a​c​c​e​s​o​ ​d​e​ ​{​r​o​l​e​}​ ​y​ ​p​r​e​p​a​r​a​n​d​o​ ​t​u​ ​d​a​s​h​b​o​a​r​d​.​.​.
		 * @param {unknown} role
		 */
		loadingLogin: RequiredParams<'role'>
		/**
		 * C​r​e​a​n​d​o​ ​c​u​e​n​t​a​ ​d​e​ ​{​r​o​l​e​}​ ​y​ ​p​r​e​p​a​r​a​n​d​o​ ​t​u​ ​d​a​s​h​b​o​a​r​d​.​.​.
		 * @param {unknown} role
		 */
		loadingRegister: RequiredParams<'role'>
		/**
		 * V​a​l​i​d​a​n​d​o​ ​e​l​ ​s​e​g​u​n​d​o​ ​f​a​c​t​o​r​ ​d​e​ ​a​u​t​e​n​t​i​c​a​c​i​ó​n​.​.​.
		 */
		loadingOtp: string
		success: {
			/**
			 * A​c​c​e​s​o​ ​c​o​n​c​e​d​i​d​o​.​ ​R​e​d​i​r​i​g​i​e​n​d​o​ ​a​l​ ​{​d​e​s​t​i​n​a​t​i​o​n​}​.
			 * @param {unknown} destination
			 */
			login: RequiredParams<'destination'>
			/**
			 * C​u​e​n​t​a​ ​c​r​e​a​d​a​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​.​ ​R​e​d​i​r​i​g​i​e​n​d​o​ ​a​l​ ​{​d​e​s​t​i​n​a​t​i​o​n​}​.
			 * @param {unknown} destination
			 */
			register: RequiredParams<'destination'>
			/**
			 * O​T​P​ ​v​a​l​i​d​a​d​o​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​.​ ​R​e​d​i​r​i​g​i​e​n​d​o​ ​a​l​ ​{​d​e​s​t​i​n​a​t​i​o​n​}​.
			 * @param {unknown} destination
			 */
			otp: RequiredParams<'destination'>
			/**
			 * S​e​s​i​ó​n​ ​i​n​i​c​i​a​d​a​ ​c​o​n​ ​G​o​o​g​l​e​.​ ​R​e​d​i​r​i​g​i​e​n​d​o​ ​a​l​ ​{​d​e​s​t​i​n​a​t​i​o​n​}​.
			 * @param {unknown} destination
			 */
			google: RequiredParams<'destination'>
			/**
			 * S​e​ ​g​e​n​e​r​ó​ ​u​n​ ​O​T​P​ ​t​e​m​p​o​r​a​l​.​ ​I​n​g​r​e​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​p​a​r​a​ ​c​o​n​t​i​n​u​a​r​.
			 */
			otpSent: string
			/**
			 * S​e​ ​g​e​n​e​r​ó​ ​u​n​ ​O​T​P​ ​t​e​m​p​o​r​a​l​.​ ​P​a​r​a​ ​p​r​u​e​b​a​s​ ​l​o​c​a​l​e​s​,​ ​u​s​a​ ​e​l​ ​c​ó​d​i​g​o​ ​{​c​o​d​e​}​.
			 * @param {unknown} code
			 */
			otpSentWithPreview: RequiredParams<'code'>
		}
		roleDescription: {
			/**
			 * R​e​v​i​s​a​ ​e​l​ ​e​s​t​a​d​o​ ​y​ ​r​e​t​i​r​o​ ​d​e​ ​t​u​s​ ​e​n​c​o​m​i​e​n​d​a​s​.
			 */
			residente: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​ ​i​n​g​r​e​s​o​s​ ​e​ ​h​i​s​t​o​r​i​a​l​ ​d​e​ ​e​n​c​o​m​i​e​n​d​a​s​.
			 */
			conserje: string
			/**
			 * R​e​v​i​s​a​ ​e​l​ ​e​s​t​a​d​o​ ​y​ ​r​e​t​i​r​o​ ​d​e​ ​t​u​s​ ​e​n​c​o​m​i​e​n​d​a​s​.
			 */
			resident: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​ ​i​n​g​r​e​s​o​s​ ​e​ ​h​i​s​t​o​r​i​a​l​ ​d​e​ ​e​n​c​o​m​i​e​n​d​a​s​.
			 */
			concierge: string
			/**
			 * G​e​s​t​i​o​n​a​ ​u​s​u​a​r​i​o​s​,​ ​r​o​l​e​s​ ​y​ ​c​o​n​f​i​g​u​r​a​c​i​ó​n​ ​d​e​l​ ​s​i​s​t​e​m​a​.
			 */
			administrator: string
		}
		field: {
			/**
			 * N​o​m​b​r​e​ ​c​o​m​p​l​e​t​o
			 */
			name: string
			/**
			 * E​m​a​i​l
			 */
			email: string
			/**
			 * N​o​m​b​r​e​ ​d​e​ ​u​s​u​a​r​i​o
			 */
			username: string
			/**
			 * E​m​a​i​l​ ​o​ ​u​s​u​a​r​i​o
			 */
			identifier: string
			/**
			 * C​o​n​t​r​a​s​e​ñ​a
			 */
			password: string
			/**
			 * C​o​n​f​i​r​m​a​r​ ​c​o​n​t​r​a​s​e​ñ​a
			 */
			confirmPassword: string
			/**
			 * C​ó​d​i​g​o​ ​O​T​P
			 */
			otpCode: string
		}
		placeholder: {
			/**
			 * E​j​:​ ​M​a​r​t​i​n​a​ ​S​o​t​o
			 */
			name: string
			/**
			 * E​j​:​ ​u​s​u​a​r​i​o​@​e​n​c​o​m​b​o​x​.​c​l
			 */
			email: string
			/**
			 * C​r​e​a​ ​t​u​ ​u​s​u​a​r​i​o
			 */
			username: string
			identifier: {
				/**
				 * E​j​:​ ​r​e​s​i​d​e​n​t​e​ ​o​ ​r​e​s​i​d​e​n​t​e​@​e​n​c​o​m​b​o​x​.​c​l
				 */
				residente: string
				/**
				 * E​j​:​ ​c​o​n​s​e​r​j​e​ ​o​ ​c​o​n​s​e​r​j​e​@​e​n​c​o​m​b​o​x​.​c​l
				 */
				conserje: string
				/**
				 * E​j​:​ ​a​d​m​i​n​ ​o​ ​a​d​m​i​n​@​e​n​c​o​m​b​o​x​.​c​l
				 */
				administrador: string
			}
			password: {
				/**
				 * I​n​g​r​e​s​a​ ​t​u​ ​c​o​n​t​r​a​s​e​ñ​a
				 */
				login: string
				/**
				 * C​r​e​a​ ​u​n​a​ ​c​o​n​t​r​a​s​e​ñ​a​ ​s​e​g​u​r​a
				 */
				register: string
			}
			/**
			 * R​e​p​i​t​e​ ​t​u​ ​c​o​n​t​r​a​s​e​ñ​a
			 */
			confirmPassword: string
			/**
			 * I​n​g​r​e​s​a​ ​l​o​s​ ​6​ ​d​í​g​i​t​o​s
			 */
			otpCode: string
		}
		validation: {
			identifier: {
				/**
				 * I​n​g​r​e​s​a​ ​t​u​ ​e​m​a​i​l​ ​i​n​s​t​i​t​u​c​i​o​n​a​l​ ​o​ ​t​u​ ​u​s​u​a​r​i​o​.
				 */
				required: string
				/**
				 * E​l​ ​f​o​r​m​a​t​o​ ​d​e​l​ ​e​m​a​i​l​ ​n​o​ ​e​s​ ​v​á​l​i​d​o​.
				 */
				invalidEmail: string
			}
			password: {
				/**
				 * I​n​g​r​e​s​a​ ​t​u​ ​c​o​n​t​r​a​s​e​ñ​a​ ​p​a​r​a​ ​c​o​n​t​i​n​u​a​r​.
				 */
				required: string
				/**
				 * L​a​ ​c​o​n​t​r​a​s​e​ñ​a​ ​d​e​b​e​ ​t​e​n​e​r​ ​a​l​ ​m​e​n​o​s​ ​8​ ​c​a​r​a​c​t​e​r​e​s​.
				 */
				min: string
				/**
				 * C​r​e​a​ ​u​n​a​ ​c​o​n​t​r​a​s​e​ñ​a​ ​p​a​r​a​ ​t​u​ ​c​u​e​n​t​a​.
				 */
				create: string
			}
			name: {
				/**
				 * I​n​g​r​e​s​a​ ​t​u​ ​n​o​m​b​r​e​ ​c​o​m​p​l​e​t​o​.
				 */
				required: string
				/**
				 * I​n​g​r​e​s​a​ ​u​n​ ​n​o​m​b​r​e​ ​m​á​s​ ​c​o​m​p​l​e​t​o​.
				 */
				min: string
			}
			email: {
				/**
				 * I​n​g​r​e​s​a​ ​t​u​ ​e​m​a​i​l​.
				 */
				required: string
				/**
				 * E​l​ ​f​o​r​m​a​t​o​ ​d​e​l​ ​e​m​a​i​l​ ​n​o​ ​e​s​ ​v​á​l​i​d​o​.
				 */
				invalid: string
			}
			username: {
				/**
				 * C​r​e​a​ ​u​n​ ​n​o​m​b​r​e​ ​d​e​ ​u​s​u​a​r​i​o​.
				 */
				required: string
				/**
				 * U​s​a​ ​e​n​t​r​e​ ​4​ ​y​ ​2​0​ ​c​a​r​a​c​t​e​r​e​s​ ​s​i​n​ ​e​s​p​a​c​i​o​s​.
				 */
				invalid: string
			}
			confirmPassword: {
				/**
				 * C​o​n​f​i​r​m​a​ ​t​u​ ​c​o​n​t​r​a​s​e​ñ​a​.
				 */
				required: string
				/**
				 * L​a​s​ ​c​o​n​t​r​a​s​e​ñ​a​s​ ​n​o​ ​c​o​i​n​c​i​d​e​n​.
				 */
				match: string
			}
			otpCode: {
				/**
				 * I​n​g​r​e​s​a​ ​u​n​ ​c​ó​d​i​g​o​ ​O​T​P​ ​d​e​ ​6​ ​d​í​g​i​t​o​s​.
				 */
				invalid: string
			}
		}
		status: {
			/**
			 * I​n​g​r​e​s​a​n​d​o​.​.​.
			 */
			loggingIn: string
			/**
			 * R​e​g​i​s​t​r​a​n​d​o​.​.​.
			 */
			registering: string
			/**
			 * V​a​l​i​d​a​n​d​o​ ​O​T​P​.​.​.
			 */
			verifyingOtp: string
		}
		destination: {
			/**
			 * p​a​n​e​l​ ​d​e​l​ ​r​e​s​i​d​e​n​t​e
			 */
			residente: string
			/**
			 * p​a​n​e​l​ ​d​e​ ​c​o​n​s​e​r​j​e​r​í​a
			 */
			conserje: string
			/**
			 * p​a​n​e​l​ ​d​e​ ​a​d​m​i​n​i​s​t​r​a​c​i​ó​n
			 */
			administrador: string
		}
		/**
		 * S​e​g​u​n​d​o​ ​f​a​c​t​o​r​ ​p​a​r​a​ ​{​r​o​l​e​}​ ​c​o​n​ ​i​d​e​n​t​i​f​i​c​a​d​o​r​ ​{​i​d​e​n​t​i​f​i​e​r​}​.
		 * @param {unknown} identifier
		 * @param {unknown} role
		 */
		otpSummary: RequiredParams<'identifier' | 'role'>
		/**
		 * E​l​ ​c​ó​d​i​g​o​ ​e​x​p​i​r​a​ ​a​ ​l​a​s​ ​{​e​x​p​i​r​e​s​A​t​}​.
		 * @param {unknown} expiresAt
		 */
		otpExpiresAt: RequiredParams<'expiresAt'>
		errors: {
			/**
			 * N​o​ ​p​u​d​i​m​o​s​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​c​i​o​ ​d​e​ ​a​u​t​e​n​t​i​c​a​c​i​ó​n​.​ ​R​e​v​i​s​a​ ​t​u​ ​r​e​d​ ​e​ ​i​n​t​e​n​t​a​ ​o​t​r​a​ ​v​e​z​.
			 */
			networkLogin: string
			/**
			 * N​o​ ​p​u​d​i​m​o​s​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​c​i​o​ ​d​e​ ​r​e​g​i​s​t​r​o​.​ ​R​e​v​i​s​a​ ​t​u​ ​r​e​d​ ​e​ ​i​n​t​e​n​t​a​ ​o​t​r​a​ ​v​e​z​.
			 */
			networkRegister: string
			/**
			 * N​o​ ​p​u​d​i​m​o​s​ ​v​a​l​i​d​a​r​ ​e​l​ ​O​T​P​.​ ​R​e​v​i​s​a​ ​t​u​ ​c​o​n​e​x​i​ó​n​ ​e​ ​i​n​t​e​n​t​a​ ​n​u​e​v​a​m​e​n​t​e​.
			 */
			networkOtp: string
			/**
			 * U​s​u​a​r​i​o​,​ ​e​m​a​i​l​ ​o​ ​c​o​n​t​r​a​s​e​ñ​a​ ​i​n​c​o​r​r​e​c​t​o​s​.​ ​V​e​r​i​f​i​c​a​ ​l​o​s​ ​d​a​t​o​s​ ​e​ ​i​n​t​e​n​t​a​ ​n​u​e​v​a​m​e​n​t​e​.
			 */
			invalidCredentials: string
			/**
			 * E​l​ ​c​ó​d​i​g​o​ ​O​T​P​ ​e​s​ ​i​n​c​o​r​r​e​c​t​o​.​ ​V​e​r​i​f​i​c​a​ ​l​o​s​ ​6​ ​d​í​g​i​t​o​s​ ​e​ ​i​n​t​e​n​t​a​ ​n​u​e​v​a​m​e​n​t​e​.
			 */
			invalidOtp: string
			/**
			 * E​l​ ​O​T​P​ ​e​x​p​i​r​ó​.​ ​D​e​b​e​s​ ​v​o​l​v​e​r​ ​a​ ​i​n​i​c​i​a​r​ ​s​e​s​i​ó​n​ ​p​a​r​a​ ​g​e​n​e​r​a​r​ ​u​n​o​ ​n​u​e​v​o​.
			 */
			otpExpired: string
			/**
			 * E​l​ ​s​e​r​v​i​c​i​o​ ​d​e​ ​a​u​t​e​n​t​i​c​a​c​i​ó​n​ ​r​e​s​p​o​n​d​i​ó​ ​c​o​n​ ​u​n​ ​f​o​r​m​a​t​o​ ​i​n​v​á​l​i​d​o​.
			 */
			invalidResponse: string
			/**
			 * Y​a​ ​e​x​i​s​t​e​ ​u​n​a​ ​c​u​e​n​t​a​ ​c​o​n​ ​e​s​e​ ​e​m​a​i​l​ ​o​ ​n​o​m​b​r​e​ ​d​e​ ​u​s​u​a​r​i​o​.
			 */
			userAlreadyExists: string
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​c​o​m​p​l​e​t​a​r​ ​e​l​ ​a​c​c​e​s​o​ ​c​o​n​ ​G​o​o​g​l​e​.​ ​I​n​t​e​n​t​a​ ​n​u​e​v​a​m​e​n​t​e​.
			 */
			googleLogin: string
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​c​o​m​p​l​e​t​a​r​ ​l​a​ ​a​u​t​e​n​t​i​c​a​c​i​ó​n​.​ ​I​n​t​e​n​t​a​ ​n​u​e​v​a​m​e​n​t​e​ ​e​n​ ​u​n​o​s​ ​s​e​g​u​n​d​o​s​.
			 */
			generic: string
		}
	}
	layout: {
		/**
		 * N​a​v​e​g​a​c​i​ó​n
		 */
		navigation: string
		/**
		 * M​e​n​ú
		 */
		menu: string
	}
	historial: {
		/**
		 * H​i​s​t​o​r​i​a​l​ ​d​e​ ​e​n​c​o​m​i​e​n​d​a​s
		 */
		title: string
		/**
		 * R​e​v​i​s​a​ ​t​o​d​a​s​ ​l​a​s​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​g​i​s​t​r​a​d​a​s​ ​y​ ​s​u​ ​e​s​t​a​d​o​ ​a​c​t​u​a​l​.
		 */
		description: string
		/**
		 * R​e​v​i​s​a​ ​t​o​d​a​s​ ​l​a​s​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​g​i​s​t​r​a​d​a​s​ ​y​ ​a​c​t​u​a​l​i​z​a​ ​s​u​ ​e​s​t​a​d​o​ ​c​u​a​n​d​o​ ​e​l​ ​r​e​s​i​d​e​n​t​e​ ​l​a​ ​r​e​t​i​r​e​.
		 */
		description_conserje: string
		/**
		 * R​e​v​i​s​a​ ​s​o​l​o​ ​t​u​s​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​g​i​s​t​r​a​d​a​s​ ​y​ ​e​l​ ​e​s​t​a​d​o​ ​e​n​ ​q​u​e​ ​s​e​ ​e​n​c​u​e​n​t​r​a​n​.
		 */
		description_residente: string
		filter: {
			/**
			 * M​o​s​t​r​a​n​d​o​ ​e​n​c​o​m​i​e​n​d​a​s​ ​a​s​o​c​i​a​d​a​s​ ​a​ ​{​r​e​c​i​p​i​e​n​t​}​.
			 * @param {unknown} recipient
			 */
			mine: RequiredParams<'recipient'>
		}
		/**
		 * S​e​ ​a​g​r​e​g​ó​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​ ​l​a​ ​e​n​c​o​m​i​e​n​d​a​ ​d​e​ ​{​r​e​c​i​p​i​e​n​t​}​ ​y​ ​y​a​ ​s​e​ ​e​n​c​u​e​n​t​r​a​ ​e​n​ ​e​l​ ​h​i​s​t​o​r​i​a​l​.
		 * @param {unknown} recipient
		 */
		recentSuccess: RequiredParams<'recipient'>
		/**
		 * e​s​t​e​ ​r​e​s​i​d​e​n​t​e
		 */
		recentRecipientFallback: string
		/**
		 * C​a​r​g​a​n​d​o​ ​e​n​c​o​m​i​e​n​d​a​s​.​.​.
		 */
		loading: string
		error: {
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​c​a​r​g​a​r​ ​e​l​ ​h​i​s​t​o​r​i​a​l​.
			 */
			load: string
			/**
			 * E​r​r​o​r​ ​a​l​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​d​o​r​.
			 */
			network: string
		}
		/**
		 * A​ú​n​ ​n​o​ ​h​a​y​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​g​i​s​t​r​a​d​a​s​.
		 */
		empty: string
		/**
		 * T​o​d​a​v​í​a​ ​n​o​ ​h​a​y​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​g​i​s​t​r​a​d​a​s​ ​a​ ​t​u​ ​n​o​m​b​r​e​.
		 */
		empty_residente: string
		table: {
			/**
			 * R​e​s​i​d​e​n​t​e
			 */
			resident: string
			/**
			 * D​e​p​t​o
			 */
			apartment: string
			/**
			 * R​e​m​i​t​e​n​t​e
			 */
			sender: string
			/**
			 * F​e​c​h​a​ ​e​n​t​r​e​g​a
			 */
			deliveryDate: string
			/**
			 * R​e​g​i​s​t​r​a​d​a
			 */
			createdAt: string
			/**
			 * F​e​c​h​a​ ​d​e​ ​r​e​t​i​r​o
			 */
			retrievedAt: string
			/**
			 * E​s​t​a​d​o
			 */
			status: string
			/**
			 * A​c​c​i​o​n​e​s
			 */
			actions: string
		}
		date: {
			/**
			 * S​i​n​ ​f​e​c​h​a
			 */
			none: string
			/**
			 * F​e​c​h​a​ ​n​o​ ​v​á​l​i​d​a
			 */
			invalid: string
			/**
			 * P​e​n​d​i​e​n​t​e
			 */
			pending: string
		}
		status: {
			/**
			 * R​e​c​i​b​i​d​a
			 */
			received: string
			/**
			 * E​n​t​r​e​g​a​d​a
			 */
			delivered: string
			/**
			 * P​e​n​d​i​e​n​t​e
			 */
			pending: string
		}
		action: {
			/**
			 * M​a​r​c​a​r​ ​c​o​m​o​ ​e​n​t​r​e​g​a​d​a
			 */
			markDelivered: string
			/**
			 * E​d​i​t​a​r
			 */
			edit: string
			/**
			 * E​d​i​t​a​n​d​o
			 */
			editing: string
			/**
			 * A​c​t​u​a​l​i​z​a​n​d​o​.​.​.
			 */
			updating: string
			/**
			 * Y​a​ ​e​n​t​r​e​g​a​d​a
			 */
			alreadyDelivered: string
			/**
			 * E​l​i​m​i​n​a​r
			 */
			'delete': string
			/**
			 * E​l​i​m​i​n​a​n​d​o​.​.​.
			 */
			deleting: string
		}
		'delete': {
			/**
			 * E​l​i​m​i​n​a​r​ ​e​n​c​o​m​i​e​n​d​a
			 */
			title: string
			/**
			 * ¿​S​e​g​u​r​o​ ​q​u​e​ ​d​e​s​e​a​s​ ​e​l​i​m​i​n​a​r​ ​l​a​ ​e​n​c​o​m​i​e​n​d​a​ ​d​e​ ​{​{​r​e​c​i​p​i​e​n​t​}​}​?​ ​E​s​t​a​ ​a​c​c​i​ó​n​ ​n​o​ ​s​e​ ​p​u​e​d​e​ ​d​e​s​h​a​c​e​r​.
			 */
			message: string
			/**
			 * E​l​i​m​i​n​a​r
			 */
			confirm: string
			/**
			 * L​a​ ​e​n​c​o​m​i​e​n​d​a​ ​d​e​ ​{​{​r​e​c​i​p​i​e​n​t​}​}​ ​f​u​e​ ​e​l​i​m​i​n​a​d​a​.
			 */
			success: string
		}
		statusUpdate: {
			/**
			 * L​a​ ​e​n​c​o​m​i​e​n​d​a​ ​d​e​ ​{​r​e​c​i​p​i​e​n​t​}​ ​f​u​e​ ​m​a​r​c​a​d​a​ ​c​o​m​o​ ​e​n​t​r​e​g​a​d​a​.
			 * @param {unknown} recipient
			 */
			success: RequiredParams<'recipient'>
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​a​c​t​u​a​l​i​z​a​r​ ​e​l​ ​e​s​t​a​d​o​ ​d​e​ ​l​a​ ​e​n​c​o​m​i​e​n​d​a​.
			 */
			error: string
		}
		edit: {
			/**
			 * E​d​i​t​a​r​ ​e​n​c​o​m​i​e​n​d​a
			 */
			title: string
			/**
			 * C​o​r​r​i​g​e​ ​l​o​s​ ​d​a​t​o​s​ ​r​e​g​i​s​t​r​a​d​o​s​ ​y​ ​g​u​a​r​d​a​ ​l​o​s​ ​c​a​m​b​i​o​s​ ​e​n​ ​e​l​ ​b​a​c​k​e​n​d​.
			 */
			description: string
			field: {
				/**
				 * O​b​s​e​r​v​a​c​i​o​n​e​s
				 */
				description: string
			}
			/**
			 * G​u​a​r​d​a​n​d​o​.​.​.
			 */
			saving: string
			/**
			 * L​a​ ​e​n​c​o​m​i​e​n​d​a​ ​d​e​ ​{​r​e​c​i​p​i​e​n​t​}​ ​f​u​e​ ​a​c​t​u​a​l​i​z​a​d​a​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​.
			 * @param {unknown} recipient
			 */
			success: RequiredParams<'recipient'>
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​g​u​a​r​d​a​r​ ​l​a​ ​e​d​i​c​i​ó​n​.
			 */
			error: string
			validation: {
				recipient: {
					/**
					 * E​l​ ​n​o​m​b​r​e​ ​d​e​l​ ​r​e​s​i​d​e​n​t​e​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
					 */
					required: string
				}
				apartment: {
					/**
					 * E​l​ ​d​e​p​a​r​t​a​m​e​n​t​o​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
					 */
					required: string
					/**
					 * U​s​a​ ​u​n​ ​f​o​r​m​a​t​o​ ​v​á​l​i​d​o​,​ ​p​o​r​ ​e​j​e​m​p​l​o​ ​1​0​1​ ​o​ ​A​-​1​2​.
					 */
					invalid: string
				}
				sender: {
					/**
					 * E​l​ ​r​e​m​i​t​e​n​t​e​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
					 */
					required: string
				}
				deliveryDate: {
					/**
					 * L​a​ ​f​e​c​h​a​ ​n​o​ ​p​u​e​d​e​ ​s​e​r​ ​p​o​s​t​e​r​i​o​r​ ​a​l​ ​d​í​a​ ​a​c​t​u​a​l​.
					 */
					future: string
				}
				status: {
					/**
					 * S​e​l​e​c​c​i​o​n​a​ ​u​n​ ​e​s​t​a​d​o​ ​p​a​r​a​ ​l​a​ ​e​n​c​o​m​i​e​n​d​a​.
					 */
					required: string
				}
				/**
				 * C​o​r​r​i​g​e​ ​l​o​s​ ​c​a​m​p​o​s​ ​m​a​r​c​a​d​o​s​ ​a​n​t​e​s​ ​d​e​ ​g​u​a​r​d​a​r​ ​l​a​ ​e​d​i​c​i​ó​n​.
				 */
				general: string
			}
		}
	}
	conserje: {
		/**
		 * R​e​g​i​s​t​r​a​r​ ​e​n​c​o​m​i​e​n​d​a
		 */
		title: string
		field: {
			/**
			 * N​o​m​b​r​e​ ​r​e​s​i​d​e​n​t​e​ ​*
			 */
			recipient: string
			/**
			 * C​o​r​r​e​o​ ​r​e​s​i​d​e​n​t​e​ ​*
			 */
			recipientEmail: string
			/**
			 * D​e​p​a​r​t​a​m​e​n​t​o​ ​*
			 */
			apartment: string
			/**
			 * R​e​m​i​t​e​n​t​e​ ​*
			 */
			sender: string
			/**
			 * F​e​c​h​a​ ​d​e​ ​e​n​t​r​e​g​a​ ​*
			 */
			deliveryDate: string
			/**
			 * U​r​g​e​n​c​i​a
			 */
			urgency: string
		}
		placeholder: {
			/**
			 * E​j​:​ ​C​a​m​i​l​a​ ​S​o​t​o
			 */
			recipient: string
			/**
			 * E​j​:​ ​c​a​m​i​l​a​@​e​n​c​o​m​b​o​x​.​c​l
			 */
			recipientEmail: string
			/**
			 * E​j​:​ ​1​0​1​ ​o​ ​A​-​1​2
			 */
			apartment: string
			/**
			 * E​j​:​ ​M​e​r​c​a​d​o​ ​L​i​b​r​e
			 */
			sender: string
		}
		/**
		 * F​e​c​h​a​ ​m​á​x​i​m​a​ ​p​e​r​m​i​t​i​d​a​:​ ​{​d​a​t​e​}
		 * @param {unknown} date
		 */
		maxDate: RequiredParams<'date'>
		urgency: {
			/**
			 * N​o​ ​u​r​g​e​n​t​e
			 */
			normal: string
			/**
			 * U​r​g​e​n​t​e
			 */
			urgent: string
			/**
			 * S​e​ ​r​e​g​i​s​t​r​a​r​á​ ​c​o​m​o​ ​n​o​ ​u​r​g​e​n​t​e​ ​e​n​ ​e​s​t​a​ ​p​a​n​t​a​l​l​a​.
			 */
			normalHelp: string
			/**
			 * S​e​ ​m​a​r​c​a​r​á​ ​v​i​s​u​a​l​m​e​n​t​e​ ​c​o​m​o​ ​u​r​g​e​n​t​e​ ​e​n​ ​e​s​t​a​ ​p​a​n​t​a​l​l​a​.
			 */
			urgentHelp: string
		}
		validation: {
			recipient: {
				/**
				 * E​l​ ​n​o​m​b​r​e​ ​d​e​l​ ​r​e​s​i​d​e​n​t​e​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
				 */
				required: string
			}
			recipientEmail: {
				/**
				 * E​l​ ​c​o​r​r​e​o​ ​d​e​l​ ​r​e​s​i​d​e​n​t​e​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​ ​p​a​r​a​ ​e​n​v​i​a​r​ ​e​l​ ​Q​R​.
				 */
				required: string
				/**
				 * I​n​g​r​e​s​a​ ​u​n​ ​c​o​r​r​e​o​ ​v​á​l​i​d​o​ ​p​a​r​a​ ​e​n​v​i​a​r​ ​e​l​ ​Q​R​.
				 */
				invalid: string
			}
			apartment: {
				/**
				 * E​l​ ​d​e​p​a​r​t​a​m​e​n​t​o​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
				 */
				required: string
				/**
				 * U​s​a​ ​u​n​ ​f​o​r​m​a​t​o​ ​v​á​l​i​d​o​,​ ​p​o​r​ ​e​j​e​m​p​l​o​ ​1​0​1​ ​o​ ​A​-​1​2​.
				 */
				invalid: string
			}
			sender: {
				/**
				 * E​l​ ​r​e​m​i​t​e​n​t​e​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​o​.
				 */
				required: string
			}
			deliveryDate: {
				/**
				 * L​a​ ​f​e​c​h​a​ ​e​s​ ​o​b​l​i​g​a​t​o​r​i​a​.
				 */
				required: string
				/**
				 * L​a​ ​f​e​c​h​a​ ​n​o​ ​p​u​e​d​e​ ​s​e​r​ ​p​o​s​t​e​r​i​o​r​ ​a​l​ ​d​í​a​ ​a​c​t​u​a​l​.
				 */
				future: string
			}
			/**
			 * C​o​r​r​i​g​e​ ​l​o​s​ ​c​a​m​p​o​s​ ​m​a​r​c​a​d​o​s​ ​a​n​t​e​s​ ​d​e​ ​c​o​n​t​i​n​u​a​r​.
			 */
			general: string
		}
		error: {
			/**
			 * E​r​r​o​r​ ​a​l​ ​r​e​g​i​s​t​r​a​r​ ​l​a​ ​e​n​c​o​m​i​e​n​d​a​.
			 */
			submit: string
			/**
			 * E​r​r​o​r​ ​a​l​ ​c​o​n​e​c​t​a​r​ ​c​o​n​ ​e​l​ ​s​e​r​v​i​d​o​r​.
			 */
			network: string
		}
		/**
		 * E​n​c​o​m​i​e​n​d​a​ ​r​e​g​i​s​t​r​a​d​a​ ​c​o​r​r​e​c​t​a​m​e​n​t​e​ ​c​o​m​o​ ​{​u​r​g​e​n​c​y​}​.
		 * @param {unknown} urgency
		 */
		success: RequiredParams<'urgency'>
		success_urgency: {
			/**
			 * u​r​g​e​n​t​e
			 */
			urgent: string
			/**
			 * n​o​ ​u​r​g​e​n​t​e
			 */
			normal: string
		}
		/**
		 * R​e​g​i​s​t​r​a​r​ ​e​n​c​o​m​i​e​n​d​a
		 */
		submit: string
		/**
		 * R​e​g​i​s​t​r​a​n​d​o​.​.​.
		 */
		submitting: string
		verify: {
			/**
			 * V​e​r​i​f​i​c​a​r​ ​Q​R​ ​d​e​ ​r​e​t​i​r​o
			 */
			title: string
			/**
			 * E​s​c​a​n​e​a​ ​e​l​ ​Q​R​ ​q​u​e​ ​r​e​c​i​b​i​ó​ ​e​l​ ​r​e​s​i​d​e​n​t​e​ ​p​o​r​ ​c​o​r​r​e​o​.​ ​S​i​ ​e​s​ ​v​á​l​i​d​o​,​ ​l​a​ ​e​n​c​o​m​i​e​n​d​a​ ​s​e​ ​m​a​r​c​a​r​á​ ​c​o​m​o​ ​e​n​t​r​e​g​a​d​a​.
			 */
			description: string
			/**
			 * L​a​ ​e​n​c​o​m​i​e​n​d​a​ ​d​e​ ​{​r​e​c​i​p​i​e​n​t​}​ ​f​u​e​ ​v​a​l​i​d​a​d​a​ ​y​ ​e​n​t​r​e​g​a​d​a​.
			 * @param {unknown} recipient
			 */
			success: RequiredParams<'recipient'>
			/**
			 * N​o​ ​s​e​ ​p​u​d​o​ ​v​a​l​i​d​a​r​ ​e​l​ ​Q​R​ ​d​e​ ​r​e​t​i​r​o​.
			 */
			error: string
			scanner: {
				/**
				 * E​s​c​a​n​e​a​r​ ​Q​R
				 */
				start: string
				/**
				 * D​e​t​e​n​e​r​ ​c​á​m​a​r​a
				 */
				stop: string
				/**
				 * A​p​u​n​t​a​ ​l​a​ ​c​á​m​a​r​a​ ​a​l​ ​Q​R​ ​q​u​e​ ​r​e​c​i​b​i​ó​ ​e​l​ ​r​e​s​i​d​e​n​t​e​ ​e​n​ ​s​u​ ​c​o​r​r​e​o​.
				 */
				help: string
				/**
				 * N​o​ ​s​e​ ​p​u​d​o​ ​i​n​i​c​i​a​r​ ​l​a​ ​c​á​m​a​r​a​ ​p​a​r​a​ ​e​s​c​a​n​e​a​r​ ​e​l​ ​Q​R​.​ ​R​e​v​i​s​a​ ​p​e​r​m​i​s​o​s​ ​e​ ​i​n​t​e​n​t​a​ ​n​u​e​v​a​m​e​n​t​e​.
				 */
				error: string
			}
			/**
			 * R​e​t​i​r​o​ ​c​o​n​f​i​r​m​a​d​o
			 */
			resultTitle: string
			/**
			 * R​e​s​i​d​e​n​t​e​:​ ​{​r​e​c​i​p​i​e​n​t​}
			 * @param {unknown} recipient
			 */
			resultRecipient: RequiredParams<'recipient'>
			/**
			 * D​e​p​a​r​t​a​m​e​n​t​o​:​ ​{​a​p​a​r​t​m​e​n​t​}
			 * @param {unknown} apartment
			 */
			resultApartment: RequiredParams<'apartment'>
			/**
			 * R​e​m​i​t​e​n​t​e​:​ ​{​s​e​n​d​e​r​}
			 * @param {unknown} sender
			 */
			resultSender: RequiredParams<'sender'>
		}
	}
	residente: {
		/**
		 * M​i​s​ ​e​n​c​o​m​i​e​n​d​a​s
		 */
		title: string
		/**
		 * C​o​n​s​u​l​t​a​ ​t​u​s​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​c​i​e​n​t​e​s​ ​y​ ​r​e​v​i​s​a​ ​r​á​p​i​d​a​m​e​n​t​e​ ​s​u​ ​e​s​t​a​d​o​.
		 */
		description: string
		filter: {
			/**
			 * T​a​b​l​e​r​o​ ​f​i​l​t​r​a​d​o​ ​p​a​r​a​ ​{​r​e​c​i​p​i​e​n​t​}​.
			 * @param {unknown} recipient
			 */
			mine: RequiredParams<'recipient'>
		}
		/**
		 * C​a​r​g​a​n​d​o​ ​t​u​s​ ​e​n​c​o​m​i​e​n​d​a​s​.​.​.
		 */
		loading: string
		error: {
			/**
			 * N​o​ ​s​e​ ​p​u​d​i​e​r​o​n​ ​c​a​r​g​a​r​ ​t​u​s​ ​e​n​c​o​m​i​e​n​d​a​s​.
			 */
			load: string
		}
		stats: {
			/**
			 * R​e​c​i​b​i​d​a​s
			 */
			received: string
			/**
			 * P​e​n​d​i​e​n​t​e​s
			 */
			pending: string
			/**
			 * E​n​t​r​e​g​a​d​a​s
			 */
			delivered: string
		}
		section: {
			/**
			 * Ú​l​t​i​m​a​s​ ​e​n​c​o​m​i​e​n​d​a​s
			 */
			recent: string
		}
		/**
		 * T​o​d​a​v​í​a​ ​n​o​ ​t​i​e​n​e​s​ ​e​n​c​o​m​i​e​n​d​a​s​ ​r​e​c​i​e​n​t​e​s​.
		 */
		empty: string
		item: {
			/**
			 * E​n​c​o​m​i​e​n​d​a​ ​1​ ​-​ ​E​n​t​r​e​g​a​d​a
			 */
			one: string
			/**
			 * E​n​c​o​m​i​e​n​d​a​ ​2​ ​-​ ​P​e​n​d​i​e​n​t​e
			 */
			two: string
		}
	}
	admin: {
		/**
		 * P​a​n​e​l​ ​d​e​ ​a​d​m​i​n​i​s​t​r​a​c​i​ó​n
		 */
		title: string
		/**
		 * G​e​s​t​i​o​n​a​ ​u​s​u​a​r​i​o​s​,​ ​r​o​l​e​s​ ​y​ ​e​s​t​a​d​o​s​ ​d​e​ ​a​c​c​e​s​o​ ​d​e​l​ ​s​i​s​t​e​m​a​.
		 */
		description: string
		/**
		 * U​s​u​a​r​i​o​s​ ​d​e​l​ ​s​i​s​t​e​m​a
		 */
		section: string
		count: {
			/**
			 * {​c​o​u​n​t​}​ ​u​s​u​a​r​i​o​ ​r​e​g​i​s​t​r​a​d​o
			 * @param {unknown} count
			 */
			one: RequiredParams<'count'>
			/**
			 * {​c​o​u​n​t​}​ ​u​s​u​a​r​i​o​s​ ​r​e​g​i​s​t​r​a​d​o​s
			 * @param {unknown} count
			 */
			many: RequiredParams<'count'>
		}
		/**
		 * C​a​r​g​a​n​d​o​ ​u​s​u​a​r​i​o​s​.​.​.
		 */
		loading: string
		/**
		 * N​o​ ​h​a​y​ ​u​s​u​a​r​i​o​s​ ​r​e​g​i​s​t​r​a​d​o​s​.
		 */
		empty: string
		error: {
			/**
			 * E​r​r​o​r​ ​a​l​ ​c​a​r​g​a​r​ ​u​s​u​a​r​i​o​s​.
			 */
			load: string
			/**
			 * E​r​r​o​r​ ​a​l​ ​r​e​a​l​i​z​a​r​ ​l​a​ ​a​c​c​i​ó​n​.
			 */
			action: string
		}
		table: {
			/**
			 * N​o​m​b​r​e
			 */
			name: string
			/**
			 * E​m​a​i​l​ ​/​ ​U​s​u​a​r​i​o
			 */
			identity: string
			/**
			 * R​o​l
			 */
			role: string
			/**
			 * C​a​m​b​i​a​r​ ​r​o​l
			 */
			changeRole: string
			/**
			 * E​s​t​a​d​o
			 */
			status: string
			/**
			 * A​c​c​i​o​n​e​s
			 */
			actions: string
			/**
			 * R​e​g​i​s​t​r​a​d​o
			 */
			registered: string
		}
		status: {
			/**
			 * A​c​t​i​v​o
			 */
			activo: string
			/**
			 * I​n​a​c​t​i​v​o
			 */
			inactivo: string
			/**
			 * B​l​o​q​u​e​a​d​o
			 */
			bloqueado: string
		}
		/**
		 * T​u​ ​c​u​e​n​t​a
		 */
		self: string
		/**
		 * N​o​ ​d​i​s​p​o​n​i​b​l​e
		 */
		unavailable: string
		/**
		 * G​u​a​r​d​a​r
		 */
		save: string
		/**
		 * G​u​a​r​d​a​n​d​o
		 */
		saving: string
		/**
		 * G​u​a​r​d​a​d​o
		 */
		saved: string
		action: {
			/**
			 * B​l​o​q​u​e​a​r
			 */
			block: string
			/**
			 * A​c​t​i​v​a​r
			 */
			activate: string
			/**
			 * E​l​i​m​i​n​a​r
			 */
			'delete': string
		}
		confirmation: {
			title: {
				/**
				 * C​o​n​f​i​r​m​a​r​ ​c​a​m​b​i​o​ ​d​e​ ​r​o​l
				 */
				role: string
				/**
				 * C​o​n​f​i​r​m​a​r​ ​c​a​m​b​i​o​ ​d​e​ ​e​s​t​a​d​o
				 */
				status: string
				/**
				 * C​o​n​f​i​r​m​a​r​ ​e​l​i​m​i​n​a​c​i​ó​n
				 */
				'delete': string
			}
			/**
			 * ¿​C​o​n​f​i​r​m​a​s​ ​c​a​m​b​i​a​r​ ​e​l​ ​r​o​l​ ​d​e​ ​"​{​n​a​m​e​}​"​ ​a​ ​"​{​r​o​l​e​}​"​?
			 * @param {unknown} name
			 * @param {unknown} role
			 */
			role: RequiredParams<'name' | 'role'>
			status: {
				/**
				 * ¿​C​o​n​f​i​r​m​a​s​ ​b​l​o​q​u​e​a​r​ ​l​a​ ​c​u​e​n​t​a​ ​d​e​ ​"​{​n​a​m​e​}​"​?​ ​N​o​ ​p​o​d​r​á​ ​i​n​i​c​i​a​r​ ​s​e​s​i​ó​n​.
				 * @param {unknown} name
				 */
				bloqueado: RequiredParams<'name'>
				/**
				 * ¿​C​o​n​f​i​r​m​a​s​ ​d​e​s​a​c​t​i​v​a​r​ ​l​a​ ​c​u​e​n​t​a​ ​d​e​ ​"​{​n​a​m​e​}​"​?
				 * @param {unknown} name
				 */
				inactivo: RequiredParams<'name'>
				/**
				 * ¿​C​o​n​f​i​r​m​a​s​ ​r​e​a​c​t​i​v​a​r​ ​l​a​ ​c​u​e​n​t​a​ ​d​e​ ​"​{​n​a​m​e​}​"​?
				 * @param {unknown} name
				 */
				activo: RequiredParams<'name'>
			}
			/**
			 * ¿​E​s​t​á​s​ ​s​e​g​u​r​o​ ​d​e​ ​q​u​e​ ​d​e​s​e​a​s​ ​e​l​i​m​i​n​a​r​ ​p​e​r​m​a​n​e​n​t​e​m​e​n​t​e​ ​l​a​ ​c​u​e​n​t​a​ ​d​e​ ​"​{​n​a​m​e​}​"​?​ ​E​s​t​a​ ​a​c​c​i​ó​n​ ​n​o​ ​s​e​ ​p​u​e​d​e​ ​d​e​s​h​a​c​e​r​.
			 * @param {unknown} name
			 */
			'delete': RequiredParams<'name'>
			/**
			 * A​d​v​e​r​t​e​n​c​i​a​:​ ​e​s​t​a​ ​a​c​c​i​ó​n​ ​e​l​i​m​i​n​a​r​á​ ​p​e​r​m​a​n​e​n​t​e​m​e​n​t​e​ ​a​l​ ​u​s​u​a​r​i​o​ ​y​ ​n​o​ ​p​u​e​d​e​ ​r​e​v​e​r​t​i​r​s​e​.
			 */
			warning: string
			/**
			 * P​r​o​c​e​s​a​n​d​o​.​.​.
			 */
			processing: string
			/**
			 * C​o​n​f​i​r​m​a​r
			 */
			confirm: string
		}
	}
	adminEmails: {
		/**
		 * C​o​r​r​e​o​s​ ​a​u​t​o​r​i​z​a​d​o​s
		 */
		title: string
		/**
		 * S​i​ ​s​e​ ​d​e​f​i​n​e​ ​a​l​ ​m​e​n​o​s​ ​u​n​ ​c​o​r​r​e​o​ ​p​a​r​a​ ​u​n​ ​r​o​l​,​ ​s​o​l​o​ ​e​s​o​s​ ​c​o​r​r​e​o​s​ ​p​o​d​r​á​n​ ​i​n​i​c​i​a​r​ ​s​e​s​i​ó​n​ ​c​o​n​ ​e​s​e​ ​r​o​l​.
		 */
		description: string
		/**
		 * A​g​r​e​g​a​r​ ​c​o​r​r​e​o​ ​a​u​t​o​r​i​z​a​d​o
		 */
		addSection: string
		field: {
			/**
			 * C​o​r​r​e​o​ ​e​l​e​c​t​r​ó​n​i​c​o
			 */
			email: string
			/**
			 * R​o​l
			 */
			role: string
		}
		/**
		 * u​s​u​a​r​i​o​@​e​j​e​m​p​l​o​.​c​l
		 */
		placeholder: string
		/**
		 * A​g​r​e​g​a​r
		 */
		add: string
		/**
		 * A​g​r​e​g​a​n​d​o
		 */
		adding: string
		/**
		 * C​o​r​r​e​o​s​ ​a​u​t​o​r​i​z​a​d​o​s
		 */
		listSection: string
		count: {
			/**
			 * {​c​o​u​n​t​}​ ​c​o​r​r​e​o​ ​r​e​g​i​s​t​r​a​d​o
			 * @param {unknown} count
			 */
			one: RequiredParams<'count'>
			/**
			 * {​c​o​u​n​t​}​ ​c​o​r​r​e​o​s​ ​r​e​g​i​s​t​r​a​d​o​s
			 * @param {unknown} count
			 */
			many: RequiredParams<'count'>
		}
		/**
		 * C​a​r​g​a​n​d​o​ ​c​o​r​r​e​o​s​.​.​.
		 */
		loading: string
		/**
		 * N​o​ ​h​a​y​ ​c​o​r​r​e​o​s​ ​a​u​t​o​r​i​z​a​d​o​s​.​ ​T​o​d​o​s​ ​l​o​s​ ​u​s​u​a​r​i​o​s​ ​p​u​e​d​e​n​ ​i​n​g​r​e​s​a​r​ ​a​ ​c​u​a​l​q​u​i​e​r​ ​r​o​l​.
		 */
		empty: string
		/**
		 * p​o​r​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		createdBy: RequiredParams<'name'>
		table: {
			/**
			 * C​o​r​r​e​o
			 */
			email: string
			/**
			 * R​o​l​ ​a​c​t​u​a​l
			 */
			currentRole: string
			/**
			 * C​a​m​b​i​a​r​ ​r​o​l
			 */
			changeRole: string
			/**
			 * R​e​g​i​s​t​r​a​d​o
			 */
			registered: string
			/**
			 * E​l​i​m​i​n​a​r
			 */
			'delete': string
		}
		/**
		 * G​u​a​r​d​a​r
		 */
		save: string
		/**
		 * G​u​a​r​d​a​n​d​o
		 */
		saving: string
		/**
		 * G​u​a​r​d​a​d​o
		 */
		saved: string
		/**
		 * E​l​i​m​i​n​a​r
		 */
		'delete': string
		/**
		 * E​l​i​m​i​n​a​n​d​o
		 */
		deleting: string
		error: {
			/**
			 * E​r​r​o​r​ ​a​l​ ​c​a​r​g​a​r​ ​c​o​r​r​e​o​s​ ​a​u​t​o​r​i​z​a​d​o​s​.
			 */
			load: string
			/**
			 * E​r​r​o​r​ ​a​l​ ​a​g​r​e​g​a​r​ ​c​o​r​r​e​o​.
			 */
			add: string
			/**
			 * E​r​r​o​r​ ​a​l​ ​a​c​t​u​a​l​i​z​a​r​ ​e​l​ ​r​o​l​.
			 */
			updateRole: string
			/**
			 * E​r​r​o​r​ ​a​l​ ​e​l​i​m​i​n​a​r​ ​e​l​ ​c​o​r​r​e​o​.
			 */
			'delete': string
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * EncomBox
		 */
		appName: () => LocalizedString
		locale: {
			/**
			 * Español
			 */
			es: () => LocalizedString
			/**
			 * English
			 */
			en: () => LocalizedString
		}
		/**
		 * Idioma
		 */
		language: () => LocalizedString
		/**
		 * Abrir navegación
		 */
		openMenu: () => LocalizedString
		/**
		 * Cerrar navegación
		 */
		closeMenu: () => LocalizedString
		/**
		 * Volver al login
		 */
		logout: () => LocalizedString
		/**
		 * Cargando...
		 */
		loading: () => LocalizedString
		/**
		 * Reintentar
		 */
		retry: () => LocalizedString
		/**
		 * Actualizar
		 */
		refresh: () => LocalizedString
		/**
		 * Guardar cambios
		 */
		save: () => LocalizedString
		/**
		 * Cancelar
		 */
		cancel: () => LocalizedString
		role: {
			/**
			 * residente
			 */
			residente: () => LocalizedString
			/**
			 * conserje
			 */
			conserje: () => LocalizedString
			/**
			 * administrador
			 */
			administrador: () => LocalizedString
		}
		roleLabel: {
			/**
			 * Residente
			 */
			residente: () => LocalizedString
			/**
			 * Conserje
			 */
			conserje: () => LocalizedString
			/**
			 * Administrador
			 */
			administrador: () => LocalizedString
			/**
			 * Residente
			 */
			resident: () => LocalizedString
			/**
			 * Conserje
			 */
			concierge: () => LocalizedString
			/**
			 * Administrador
			 */
			administrator: () => LocalizedString
		}
	}
	nav: {
		/**
		 * Registrar encomienda
		 */
		registerPackage: () => LocalizedString
		/**
		 * Historial
		 */
		history: () => LocalizedString
		/**
		 * Historial de encomiendas
		 */
		packageHistory: () => LocalizedString
		/**
		 * Mis encomiendas
		 */
		myPackages: () => LocalizedString
		/**
		 * Inicio
		 */
		home: () => LocalizedString
		/**
		 * Notificaciones
		 */
		notifications: () => LocalizedString
		/**
		 * Gestión de usuarios
		 */
		userManagement: () => LocalizedString
		/**
		 * Correos autorizados
		 */
		authorizedEmails: () => LocalizedString
		/**
		 * Registro de auditoría
		 */
		auditLogs: () => LocalizedString
	}
	auth: {
		mode: {
			/**
			 * Iniciar sesión
			 */
			login: () => LocalizedString
			/**
			 * Registrarse
			 */
			register: () => LocalizedString
		}
		title: {
			/**
			 * Iniciar sesión
			 */
			login: () => LocalizedString
			/**
			 * Crear cuenta
			 */
			register: () => LocalizedString
			/**
			 * Verificar código OTP
			 */
			otp: () => LocalizedString
		}
		description: {
			/**
			 * Ingresa con tu email o usuario y tu contraseña.
			 */
			login: () => LocalizedString
			/**
			 * Completa tus datos para registrarte y entrar de inmediato.
			 */
			register: () => LocalizedString
			/**
			 * Ingresa el código temporal enviado para completar el acceso de {identifier}.
			 */
			otp: (arg: { identifier: unknown }) => LocalizedString
		}
		/**
		 * Entrar como
		 */
		selectRole: () => LocalizedString
		/**
		 * Entrar como {role}
		 */
		loginButton: (arg: { role: unknown }) => LocalizedString
		/**
		 * Registrarme como {role}
		 */
		registerButton: (arg: { role: unknown }) => LocalizedString
		/**
		 * Validar código OTP
		 */
		verifyOtpButton: () => LocalizedString
		/**
		 * o continúa con
		 */
		googleDivider: () => LocalizedString
		/**
		 * Cargando acceso con Google...
		 */
		googleLoading: () => LocalizedString
		/**
		 * Validando acceso de {role} y preparando tu dashboard...
		 */
		loadingLogin: (arg: { role: unknown }) => LocalizedString
		/**
		 * Creando cuenta de {role} y preparando tu dashboard...
		 */
		loadingRegister: (arg: { role: unknown }) => LocalizedString
		/**
		 * Validando el segundo factor de autenticación...
		 */
		loadingOtp: () => LocalizedString
		success: {
			/**
			 * Acceso concedido. Redirigiendo al {destination}.
			 */
			login: (arg: { destination: unknown }) => LocalizedString
			/**
			 * Cuenta creada correctamente. Redirigiendo al {destination}.
			 */
			register: (arg: { destination: unknown }) => LocalizedString
			/**
			 * OTP validado correctamente. Redirigiendo al {destination}.
			 */
			otp: (arg: { destination: unknown }) => LocalizedString
			/**
			 * Sesión iniciada con Google. Redirigiendo al {destination}.
			 */
			google: (arg: { destination: unknown }) => LocalizedString
			/**
			 * Se generó un OTP temporal. Ingresa el código para continuar.
			 */
			otpSent: () => LocalizedString
			/**
			 * Se generó un OTP temporal. Para pruebas locales, usa el código {code}.
			 */
			otpSentWithPreview: (arg: { code: unknown }) => LocalizedString
		}
		roleDescription: {
			/**
			 * Revisa el estado y retiro de tus encomiendas.
			 */
			residente: () => LocalizedString
			/**
			 * Administra ingresos e historial de encomiendas.
			 */
			conserje: () => LocalizedString
			/**
			 * Revisa el estado y retiro de tus encomiendas.
			 */
			resident: () => LocalizedString
			/**
			 * Administra ingresos e historial de encomiendas.
			 */
			concierge: () => LocalizedString
			/**
			 * Gestiona usuarios, roles y configuración del sistema.
			 */
			administrator: () => LocalizedString
		}
		field: {
			/**
			 * Nombre completo
			 */
			name: () => LocalizedString
			/**
			 * Email
			 */
			email: () => LocalizedString
			/**
			 * Nombre de usuario
			 */
			username: () => LocalizedString
			/**
			 * Email o usuario
			 */
			identifier: () => LocalizedString
			/**
			 * Contraseña
			 */
			password: () => LocalizedString
			/**
			 * Confirmar contraseña
			 */
			confirmPassword: () => LocalizedString
			/**
			 * Código OTP
			 */
			otpCode: () => LocalizedString
		}
		placeholder: {
			/**
			 * Ej: Martina Soto
			 */
			name: () => LocalizedString
			/**
			 * Ej: usuario@encombox.cl
			 */
			email: () => LocalizedString
			/**
			 * Crea tu usuario
			 */
			username: () => LocalizedString
			identifier: {
				/**
				 * Ej: residente o residente@encombox.cl
				 */
				residente: () => LocalizedString
				/**
				 * Ej: conserje o conserje@encombox.cl
				 */
				conserje: () => LocalizedString
				/**
				 * Ej: admin o admin@encombox.cl
				 */
				administrador: () => LocalizedString
			}
			password: {
				/**
				 * Ingresa tu contraseña
				 */
				login: () => LocalizedString
				/**
				 * Crea una contraseña segura
				 */
				register: () => LocalizedString
			}
			/**
			 * Repite tu contraseña
			 */
			confirmPassword: () => LocalizedString
			/**
			 * Ingresa los 6 dígitos
			 */
			otpCode: () => LocalizedString
		}
		validation: {
			identifier: {
				/**
				 * Ingresa tu email institucional o tu usuario.
				 */
				required: () => LocalizedString
				/**
				 * El formato del email no es válido.
				 */
				invalidEmail: () => LocalizedString
			}
			password: {
				/**
				 * Ingresa tu contraseña para continuar.
				 */
				required: () => LocalizedString
				/**
				 * La contraseña debe tener al menos 8 caracteres.
				 */
				min: () => LocalizedString
				/**
				 * Crea una contraseña para tu cuenta.
				 */
				create: () => LocalizedString
			}
			name: {
				/**
				 * Ingresa tu nombre completo.
				 */
				required: () => LocalizedString
				/**
				 * Ingresa un nombre más completo.
				 */
				min: () => LocalizedString
			}
			email: {
				/**
				 * Ingresa tu email.
				 */
				required: () => LocalizedString
				/**
				 * El formato del email no es válido.
				 */
				invalid: () => LocalizedString
			}
			username: {
				/**
				 * Crea un nombre de usuario.
				 */
				required: () => LocalizedString
				/**
				 * Usa entre 4 y 20 caracteres sin espacios.
				 */
				invalid: () => LocalizedString
			}
			confirmPassword: {
				/**
				 * Confirma tu contraseña.
				 */
				required: () => LocalizedString
				/**
				 * Las contraseñas no coinciden.
				 */
				match: () => LocalizedString
			}
			otpCode: {
				/**
				 * Ingresa un código OTP de 6 dígitos.
				 */
				invalid: () => LocalizedString
			}
		}
		status: {
			/**
			 * Ingresando...
			 */
			loggingIn: () => LocalizedString
			/**
			 * Registrando...
			 */
			registering: () => LocalizedString
			/**
			 * Validando OTP...
			 */
			verifyingOtp: () => LocalizedString
		}
		destination: {
			/**
			 * panel del residente
			 */
			residente: () => LocalizedString
			/**
			 * panel de conserjería
			 */
			conserje: () => LocalizedString
			/**
			 * panel de administración
			 */
			administrador: () => LocalizedString
		}
		/**
		 * Segundo factor para {role} con identificador {identifier}.
		 */
		otpSummary: (arg: { identifier: unknown, role: unknown }) => LocalizedString
		/**
		 * El código expira a las {expiresAt}.
		 */
		otpExpiresAt: (arg: { expiresAt: unknown }) => LocalizedString
		errors: {
			/**
			 * No pudimos conectar con el servicio de autenticación. Revisa tu red e intenta otra vez.
			 */
			networkLogin: () => LocalizedString
			/**
			 * No pudimos conectar con el servicio de registro. Revisa tu red e intenta otra vez.
			 */
			networkRegister: () => LocalizedString
			/**
			 * No pudimos validar el OTP. Revisa tu conexión e intenta nuevamente.
			 */
			networkOtp: () => LocalizedString
			/**
			 * Usuario, email o contraseña incorrectos. Verifica los datos e intenta nuevamente.
			 */
			invalidCredentials: () => LocalizedString
			/**
			 * El código OTP es incorrecto. Verifica los 6 dígitos e intenta nuevamente.
			 */
			invalidOtp: () => LocalizedString
			/**
			 * El OTP expiró. Debes volver a iniciar sesión para generar uno nuevo.
			 */
			otpExpired: () => LocalizedString
			/**
			 * El servicio de autenticación respondió con un formato inválido.
			 */
			invalidResponse: () => LocalizedString
			/**
			 * Ya existe una cuenta con ese email o nombre de usuario.
			 */
			userAlreadyExists: () => LocalizedString
			/**
			 * No se pudo completar el acceso con Google. Intenta nuevamente.
			 */
			googleLogin: () => LocalizedString
			/**
			 * No se pudo completar la autenticación. Intenta nuevamente en unos segundos.
			 */
			generic: () => LocalizedString
		}
	}
	layout: {
		/**
		 * Navegación
		 */
		navigation: () => LocalizedString
		/**
		 * Menú
		 */
		menu: () => LocalizedString
	}
	historial: {
		/**
		 * Historial de encomiendas
		 */
		title: () => LocalizedString
		/**
		 * Revisa todas las encomiendas registradas y su estado actual.
		 */
		description: () => LocalizedString
		/**
		 * Revisa todas las encomiendas registradas y actualiza su estado cuando el residente la retire.
		 */
		description_conserje: () => LocalizedString
		/**
		 * Revisa solo tus encomiendas registradas y el estado en que se encuentran.
		 */
		description_residente: () => LocalizedString
		filter: {
			/**
			 * Mostrando encomiendas asociadas a {recipient}.
			 */
			mine: (arg: { recipient: unknown }) => LocalizedString
		}
		/**
		 * Se agregó correctamente la encomienda de {recipient} y ya se encuentra en el historial.
		 */
		recentSuccess: (arg: { recipient: unknown }) => LocalizedString
		/**
		 * este residente
		 */
		recentRecipientFallback: () => LocalizedString
		/**
		 * Cargando encomiendas...
		 */
		loading: () => LocalizedString
		error: {
			/**
			 * No se pudo cargar el historial.
			 */
			load: () => LocalizedString
			/**
			 * Error al conectar con el servidor.
			 */
			network: () => LocalizedString
		}
		/**
		 * Aún no hay encomiendas registradas.
		 */
		empty: () => LocalizedString
		/**
		 * Todavía no hay encomiendas registradas a tu nombre.
		 */
		empty_residente: () => LocalizedString
		table: {
			/**
			 * Residente
			 */
			resident: () => LocalizedString
			/**
			 * Depto
			 */
			apartment: () => LocalizedString
			/**
			 * Remitente
			 */
			sender: () => LocalizedString
			/**
			 * Fecha entrega
			 */
			deliveryDate: () => LocalizedString
			/**
			 * Registrada
			 */
			createdAt: () => LocalizedString
			/**
			 * Fecha de retiro
			 */
			retrievedAt: () => LocalizedString
			/**
			 * Estado
			 */
			status: () => LocalizedString
			/**
			 * Acciones
			 */
			actions: () => LocalizedString
		}
		date: {
			/**
			 * Sin fecha
			 */
			none: () => LocalizedString
			/**
			 * Fecha no válida
			 */
			invalid: () => LocalizedString
			/**
			 * Pendiente
			 */
			pending: () => LocalizedString
		}
		status: {
			/**
			 * Recibida
			 */
			received: () => LocalizedString
			/**
			 * Entregada
			 */
			delivered: () => LocalizedString
			/**
			 * Pendiente
			 */
			pending: () => LocalizedString
		}
		action: {
			/**
			 * Marcar como entregada
			 */
			markDelivered: () => LocalizedString
			/**
			 * Editar
			 */
			edit: () => LocalizedString
			/**
			 * Editando
			 */
			editing: () => LocalizedString
			/**
			 * Actualizando...
			 */
			updating: () => LocalizedString
			/**
			 * Ya entregada
			 */
			alreadyDelivered: () => LocalizedString
			/**
			 * Eliminar
			 */
			'delete': () => LocalizedString
			/**
			 * Eliminando...
			 */
			deleting: () => LocalizedString
		}
		'delete': {
			/**
			 * Eliminar encomienda
			 */
			title: () => LocalizedString
			/**
			 * ¿Seguro que deseas eliminar la encomienda de {{recipient}}? Esta acción no se puede deshacer.
			 */
			message: (arg0: number | string | boolean) => LocalizedString
			/**
			 * Eliminar
			 */
			confirm: () => LocalizedString
			/**
			 * La encomienda de {{recipient}} fue eliminada.
			 */
			success: (arg0: number | string | boolean) => LocalizedString
		}
		statusUpdate: {
			/**
			 * La encomienda de {recipient} fue marcada como entregada.
			 */
			success: (arg: { recipient: unknown }) => LocalizedString
			/**
			 * No se pudo actualizar el estado de la encomienda.
			 */
			error: () => LocalizedString
		}
		edit: {
			/**
			 * Editar encomienda
			 */
			title: () => LocalizedString
			/**
			 * Corrige los datos registrados y guarda los cambios en el backend.
			 */
			description: () => LocalizedString
			field: {
				/**
				 * Observaciones
				 */
				description: () => LocalizedString
			}
			/**
			 * Guardando...
			 */
			saving: () => LocalizedString
			/**
			 * La encomienda de {recipient} fue actualizada correctamente.
			 */
			success: (arg: { recipient: unknown }) => LocalizedString
			/**
			 * No se pudo guardar la edición.
			 */
			error: () => LocalizedString
			validation: {
				recipient: {
					/**
					 * El nombre del residente es obligatorio.
					 */
					required: () => LocalizedString
				}
				apartment: {
					/**
					 * El departamento es obligatorio.
					 */
					required: () => LocalizedString
					/**
					 * Usa un formato válido, por ejemplo 101 o A-12.
					 */
					invalid: () => LocalizedString
				}
				sender: {
					/**
					 * El remitente es obligatorio.
					 */
					required: () => LocalizedString
				}
				deliveryDate: {
					/**
					 * La fecha no puede ser posterior al día actual.
					 */
					future: () => LocalizedString
				}
				status: {
					/**
					 * Selecciona un estado para la encomienda.
					 */
					required: () => LocalizedString
				}
				/**
				 * Corrige los campos marcados antes de guardar la edición.
				 */
				general: () => LocalizedString
			}
		}
	}
	conserje: {
		/**
		 * Registrar encomienda
		 */
		title: () => LocalizedString
		field: {
			/**
			 * Nombre residente *
			 */
			recipient: () => LocalizedString
			/**
			 * Correo residente *
			 */
			recipientEmail: () => LocalizedString
			/**
			 * Departamento *
			 */
			apartment: () => LocalizedString
			/**
			 * Remitente *
			 */
			sender: () => LocalizedString
			/**
			 * Fecha de entrega *
			 */
			deliveryDate: () => LocalizedString
			/**
			 * Urgencia
			 */
			urgency: () => LocalizedString
		}
		placeholder: {
			/**
			 * Ej: Camila Soto
			 */
			recipient: () => LocalizedString
			/**
			 * Ej: camila@encombox.cl
			 */
			recipientEmail: () => LocalizedString
			/**
			 * Ej: 101 o A-12
			 */
			apartment: () => LocalizedString
			/**
			 * Ej: Mercado Libre
			 */
			sender: () => LocalizedString
		}
		/**
		 * Fecha máxima permitida: {date}
		 */
		maxDate: (arg: { date: unknown }) => LocalizedString
		urgency: {
			/**
			 * No urgente
			 */
			normal: () => LocalizedString
			/**
			 * Urgente
			 */
			urgent: () => LocalizedString
			/**
			 * Se registrará como no urgente en esta pantalla.
			 */
			normalHelp: () => LocalizedString
			/**
			 * Se marcará visualmente como urgente en esta pantalla.
			 */
			urgentHelp: () => LocalizedString
		}
		validation: {
			recipient: {
				/**
				 * El nombre del residente es obligatorio.
				 */
				required: () => LocalizedString
			}
			recipientEmail: {
				/**
				 * El correo del residente es obligatorio para enviar el QR.
				 */
				required: () => LocalizedString
				/**
				 * Ingresa un correo válido para enviar el QR.
				 */
				invalid: () => LocalizedString
			}
			apartment: {
				/**
				 * El departamento es obligatorio.
				 */
				required: () => LocalizedString
				/**
				 * Usa un formato válido, por ejemplo 101 o A-12.
				 */
				invalid: () => LocalizedString
			}
			sender: {
				/**
				 * El remitente es obligatorio.
				 */
				required: () => LocalizedString
			}
			deliveryDate: {
				/**
				 * La fecha es obligatoria.
				 */
				required: () => LocalizedString
				/**
				 * La fecha no puede ser posterior al día actual.
				 */
				future: () => LocalizedString
			}
			/**
			 * Corrige los campos marcados antes de continuar.
			 */
			general: () => LocalizedString
		}
		error: {
			/**
			 * Error al registrar la encomienda.
			 */
			submit: () => LocalizedString
			/**
			 * Error al conectar con el servidor.
			 */
			network: () => LocalizedString
		}
		/**
		 * Encomienda registrada correctamente como {urgency}.
		 */
		success: (arg: { urgency: unknown }) => LocalizedString
		success_urgency: {
			/**
			 * urgente
			 */
			urgent: () => LocalizedString
			/**
			 * no urgente
			 */
			normal: () => LocalizedString
		}
		/**
		 * Registrar encomienda
		 */
		submit: () => LocalizedString
		/**
		 * Registrando...
		 */
		submitting: () => LocalizedString
		verify: {
			/**
			 * Verificar QR de retiro
			 */
			title: () => LocalizedString
			/**
			 * Escanea el QR que recibió el residente por correo. Si es válido, la encomienda se marcará como entregada.
			 */
			description: () => LocalizedString
			/**
			 * La encomienda de {recipient} fue validada y entregada.
			 */
			success: (arg: { recipient: unknown }) => LocalizedString
			/**
			 * No se pudo validar el QR de retiro.
			 */
			error: () => LocalizedString
			scanner: {
				/**
				 * Escanear QR
				 */
				start: () => LocalizedString
				/**
				 * Detener cámara
				 */
				stop: () => LocalizedString
				/**
				 * Apunta la cámara al QR que recibió el residente en su correo.
				 */
				help: () => LocalizedString
				/**
				 * No se pudo iniciar la cámara para escanear el QR. Revisa permisos e intenta nuevamente.
				 */
				error: () => LocalizedString
			}
			/**
			 * Retiro confirmado
			 */
			resultTitle: () => LocalizedString
			/**
			 * Residente: {recipient}
			 */
			resultRecipient: (arg: { recipient: unknown }) => LocalizedString
			/**
			 * Departamento: {apartment}
			 */
			resultApartment: (arg: { apartment: unknown }) => LocalizedString
			/**
			 * Remitente: {sender}
			 */
			resultSender: (arg: { sender: unknown }) => LocalizedString
		}
	}
	residente: {
		/**
		 * Mis encomiendas
		 */
		title: () => LocalizedString
		/**
		 * Consulta tus encomiendas recientes y revisa rápidamente su estado.
		 */
		description: () => LocalizedString
		filter: {
			/**
			 * Tablero filtrado para {recipient}.
			 */
			mine: (arg: { recipient: unknown }) => LocalizedString
		}
		/**
		 * Cargando tus encomiendas...
		 */
		loading: () => LocalizedString
		error: {
			/**
			 * No se pudieron cargar tus encomiendas.
			 */
			load: () => LocalizedString
		}
		stats: {
			/**
			 * Recibidas
			 */
			received: () => LocalizedString
			/**
			 * Pendientes
			 */
			pending: () => LocalizedString
			/**
			 * Entregadas
			 */
			delivered: () => LocalizedString
		}
		section: {
			/**
			 * Últimas encomiendas
			 */
			recent: () => LocalizedString
		}
		/**
		 * Todavía no tienes encomiendas recientes.
		 */
		empty: () => LocalizedString
		item: {
			/**
			 * Encomienda 1 - Entregada
			 */
			one: () => LocalizedString
			/**
			 * Encomienda 2 - Pendiente
			 */
			two: () => LocalizedString
		}
	}
	admin: {
		/**
		 * Panel de administración
		 */
		title: () => LocalizedString
		/**
		 * Gestiona usuarios, roles y estados de acceso del sistema.
		 */
		description: () => LocalizedString
		/**
		 * Usuarios del sistema
		 */
		section: () => LocalizedString
		count: {
			/**
			 * {count} usuario registrado
			 */
			one: (arg: { count: unknown }) => LocalizedString
			/**
			 * {count} usuarios registrados
			 */
			many: (arg: { count: unknown }) => LocalizedString
		}
		/**
		 * Cargando usuarios...
		 */
		loading: () => LocalizedString
		/**
		 * No hay usuarios registrados.
		 */
		empty: () => LocalizedString
		error: {
			/**
			 * Error al cargar usuarios.
			 */
			load: () => LocalizedString
			/**
			 * Error al realizar la acción.
			 */
			action: () => LocalizedString
		}
		table: {
			/**
			 * Nombre
			 */
			name: () => LocalizedString
			/**
			 * Email / Usuario
			 */
			identity: () => LocalizedString
			/**
			 * Rol
			 */
			role: () => LocalizedString
			/**
			 * Cambiar rol
			 */
			changeRole: () => LocalizedString
			/**
			 * Estado
			 */
			status: () => LocalizedString
			/**
			 * Acciones
			 */
			actions: () => LocalizedString
			/**
			 * Registrado
			 */
			registered: () => LocalizedString
		}
		status: {
			/**
			 * Activo
			 */
			activo: () => LocalizedString
			/**
			 * Inactivo
			 */
			inactivo: () => LocalizedString
			/**
			 * Bloqueado
			 */
			bloqueado: () => LocalizedString
		}
		/**
		 * Tu cuenta
		 */
		self: () => LocalizedString
		/**
		 * No disponible
		 */
		unavailable: () => LocalizedString
		/**
		 * Guardar
		 */
		save: () => LocalizedString
		/**
		 * Guardando
		 */
		saving: () => LocalizedString
		/**
		 * Guardado
		 */
		saved: () => LocalizedString
		action: {
			/**
			 * Bloquear
			 */
			block: () => LocalizedString
			/**
			 * Activar
			 */
			activate: () => LocalizedString
			/**
			 * Eliminar
			 */
			'delete': () => LocalizedString
		}
		confirmation: {
			title: {
				/**
				 * Confirmar cambio de rol
				 */
				role: () => LocalizedString
				/**
				 * Confirmar cambio de estado
				 */
				status: () => LocalizedString
				/**
				 * Confirmar eliminación
				 */
				'delete': () => LocalizedString
			}
			/**
			 * ¿Confirmas cambiar el rol de "{name}" a "{role}"?
			 */
			role: (arg: { name: unknown, role: unknown }) => LocalizedString
			status: {
				/**
				 * ¿Confirmas bloquear la cuenta de "{name}"? No podrá iniciar sesión.
				 */
				bloqueado: (arg: { name: unknown }) => LocalizedString
				/**
				 * ¿Confirmas desactivar la cuenta de "{name}"?
				 */
				inactivo: (arg: { name: unknown }) => LocalizedString
				/**
				 * ¿Confirmas reactivar la cuenta de "{name}"?
				 */
				activo: (arg: { name: unknown }) => LocalizedString
			}
			/**
			 * ¿Estás seguro de que deseas eliminar permanentemente la cuenta de "{name}"? Esta acción no se puede deshacer.
			 */
			'delete': (arg: { name: unknown }) => LocalizedString
			/**
			 * Advertencia: esta acción eliminará permanentemente al usuario y no puede revertirse.
			 */
			warning: () => LocalizedString
			/**
			 * Procesando...
			 */
			processing: () => LocalizedString
			/**
			 * Confirmar
			 */
			confirm: () => LocalizedString
		}
	}
	adminEmails: {
		/**
		 * Correos autorizados
		 */
		title: () => LocalizedString
		/**
		 * Si se define al menos un correo para un rol, solo esos correos podrán iniciar sesión con ese rol.
		 */
		description: () => LocalizedString
		/**
		 * Agregar correo autorizado
		 */
		addSection: () => LocalizedString
		field: {
			/**
			 * Correo electrónico
			 */
			email: () => LocalizedString
			/**
			 * Rol
			 */
			role: () => LocalizedString
		}
		/**
		 * usuario@ejemplo.cl
		 */
		placeholder: () => LocalizedString
		/**
		 * Agregar
		 */
		add: () => LocalizedString
		/**
		 * Agregando
		 */
		adding: () => LocalizedString
		/**
		 * Correos autorizados
		 */
		listSection: () => LocalizedString
		count: {
			/**
			 * {count} correo registrado
			 */
			one: (arg: { count: unknown }) => LocalizedString
			/**
			 * {count} correos registrados
			 */
			many: (arg: { count: unknown }) => LocalizedString
		}
		/**
		 * Cargando correos...
		 */
		loading: () => LocalizedString
		/**
		 * No hay correos autorizados. Todos los usuarios pueden ingresar a cualquier rol.
		 */
		empty: () => LocalizedString
		/**
		 * por {name}
		 */
		createdBy: (arg: { name: unknown }) => LocalizedString
		table: {
			/**
			 * Correo
			 */
			email: () => LocalizedString
			/**
			 * Rol actual
			 */
			currentRole: () => LocalizedString
			/**
			 * Cambiar rol
			 */
			changeRole: () => LocalizedString
			/**
			 * Registrado
			 */
			registered: () => LocalizedString
			/**
			 * Eliminar
			 */
			'delete': () => LocalizedString
		}
		/**
		 * Guardar
		 */
		save: () => LocalizedString
		/**
		 * Guardando
		 */
		saving: () => LocalizedString
		/**
		 * Guardado
		 */
		saved: () => LocalizedString
		/**
		 * Eliminar
		 */
		'delete': () => LocalizedString
		/**
		 * Eliminando
		 */
		deleting: () => LocalizedString
		error: {
			/**
			 * Error al cargar correos autorizados.
			 */
			load: () => LocalizedString
			/**
			 * Error al agregar correo.
			 */
			add: () => LocalizedString
			/**
			 * Error al actualizar el rol.
			 */
			updateRole: () => LocalizedString
			/**
			 * Error al eliminar el correo.
			 */
			'delete': () => LocalizedString
		}
	}
}

export type Formatters = {}
